FROM mcr.microsoft.com/playwright:v1.43.1-focal

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx playwright install chromium --with-deps

RUN mkdir -p controller/data

ENV PORT=3000
EXPOSE 3000

CMD ["node", "server.js"]